### ISSUE TITLE
want to build yocto image before 2050KC001 for renesas RzG2LC

### ISSUE THREAD

**Issue by meera1310** [renesas-rz/meta-rzg2#2]
I have renesas processor rz/g2lc. In that processor I have date code **2050KC001** . So I am facing some issues with the latest VLP release as available on G2LC product page. For resolving this issue I wanted to have yocto image for renesas before 50th week of 2020. Please help me with this as soon as possible.

**Comment by seebe** [comment]
Please contact your local Renesas office for support.
